version: '3.8'

services:
  simon-says:
    build: .
    container_name: simon_game_web
    privileged: true
    user: "root"
    group_add:
      - gpio
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - GPIOZERO_PIN_FACTORY=lgpio
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
      - /dev/gpiochip2:/dev/gpiochip2
      - /dev/gpiochip3:/dev/gpiochip3
      - /dev/gpiochip4:/dev/gpiochip4
    restart: unless-stopped